name: cc-AD-1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - xgboost
